### ISSUE TITLE
"Could not retrieve origin data. Try again later."

### ISSUE THREAD

**Issue by Synaesthesia0** [MxMarx/lidarr-beets#4]
Hi. Now that I have found and configured beets-lidarr, I am in the process of reimporting my entire music library into Lidarr with beets tagging on import.

Out of the 100+ albums I've thrown at it so far, there have been a small handful of albums that stops beets-lidarr in its tracks, and stops the import process altogether until I restart Lidarr. After restarting, Lidarr and the import process continues until Lidarr tries again to import one of these same specific albums.

Here is the log from one of these specific album:
(NOTE it gets hung on "Looking for origin data on RED". the "Traceback" line comes up immediatly after restarting)

```
Starting auto-beets. Good luck!

╔═══════════════╤═══════════════════╗
║ artist_name   │ album_title       ║
║───────────────┼───────────────────║
║ Steven Wilson │ The Harmony Codex ║
╚═══════════════╧═══════════════════╝

2024-06-09,18:37:22 INFO     Missing API key for ops
2024-06-09,18:37:22 INFO     Found API key for red
2024-06-09,18:37:22 INFO     Found API key for lidarr
2024-06-09,18:37:22 WARNING  Can't find the grab event in history!
2024-06-09,18:37:22 INFO     album path = /data/media/music/Steven Wilson/(2023) The Harmony Codex
2024-06-09,18:37:22 INFO     torrent url = []
2024-06-09,18:37:22 INFO     torrent hash = 9C734F4CC9202E096BB0B7B643476D7A3463CF1C
2024-06-09,18:37:22 WARNING  Couldn't find the tracker url, trying RED
2024-06-09,18:37:22 INFO     Looking for origin data on RED
2024-06-09,18:53:08 WARNING  gazelle-origin-RED: Traceback (most recent call last):
  File "/lsiopy/lib/python3.12/site-packages/gazelleorigin/__main__.py", line 234, in handle_input_torrent
    info = self.api.get_torrent_info(**parsed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/gazelleorigin/core.py", line 70, in get_torrent_info
    info = self.request('torrent', hash=hash, id=id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/gazelleorigin/core.py", line 44, in request
    return self._get_parsed_response(params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/gazelleorigin/core.py", line 51, in _get_parsed_response
    raise GazelleAPIError('request',
gazelleorigin.core.GazelleAPIError: Could not retrieve origin data. Try again later. (status 400)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lsiopy/bin/gazelle-origin", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/gazelleorigin/__main__.py", line 264, in main
    gazelle_origin.run()
  File "/lsiopy/lib/python3.12/site-packages/gazelleorigin/__main__.py", line 160, in run
    self.handle_input_torrent(torrent)
  File "/lsiopy/lib/python3.12/site-packages/gazelleorigin/__main__.py", line 236, in handle_input_torrent
    if self.handle_invalid() == "stop":
       ^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/gazelleorigin/__main__.py", line 152, in handle_invalid
    result = self.ask_invalid()
             ^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/gazelleorigin/__main__.py", line 139, in ask_invalid
    do_this = input("Your choice: ")
              ^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line
2024-06-09,18:56:15 INFO
```

Otherwise this has been a fantastic script and I very much appreciate your work sharing this with the community. Thanks!

**Comment by Synaesthesia0** [comment]
Turns out these torrents couldn't be found because they had been trumped & deleted by the tracker months ago... Doh! Nothing to do with the script. Ticket closed.
